// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tranqui.Infrastructure.Persistence;

#nullable disable

namespace Tranqui.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TranquiDbContext))]
    partial class TranquiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tranqui.Domain.Appeals.Appeal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<byte[]>("PhoneHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phone_hash");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_appeals");

                    b.HasIndex("PhoneHash", "CreatedAt")
                        .HasDatabaseName("ix_appeals_phone_hash_created_at");

                    b.ToTable("appeals", (string)null);
                });

            modelBuilder.Entity("Tranqui.Domain.Appeals.AppealQuotaUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<byte[]>("SubjectKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_appeal_quota_usages");

                    b.HasIndex("SubjectKind", "SubjectKey", "Action", "UsedAt")
                        .HasDatabaseName("ix_appeal_quota_usages_subject_kind_subject_key_action_used_at");

                    b.ToTable("appeal_quota_usages", (string)null);
                });

            modelBuilder.Entity("Tranqui.Domain.Appeals.HiddenNumber", b =>
                {
                    b.Property<byte[]>("PhoneHash")
                        .HasColumnType("bytea")
                        .HasColumnName("phone_hash");

                    b.Property<DateTimeOffset>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.HasKey("PhoneHash")
                        .HasName("pk_hidden_numbers");

                    b.ToTable("hidden_numbers", (string)null);
                });

            modelBuilder.Entity("Tranqui.Domain.Reputation.ContactContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ContributedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contributed_at");

                    b.Property<byte[]>("ContributorId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("contributor_id");

                    b.Property<int>("HashKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("hash_key_version");

                    b.Property<byte[]>("NameCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("name_ciphertext");

                    b.Property<byte[]>("NameGroupingKey")
                        .HasColumnType("bytea")
                        .HasColumnName("name_grouping_key");

                    b.Property<byte[]>("PhoneHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phone_hash");

                    b.HasKey("Id")
                        .HasName("pk_contact_contributions");

                    b.HasIndex("PhoneHash", "ContributorId")
                        .IsUnique()
                        .HasDatabaseName("ix_contact_contributions_phone_hash_contributor_id");

                    b.ToTable("contact_contributions", (string)null);
                });

            modelBuilder.Entity("Tranqui.Domain.Reputation.SpamReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ContributorId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("contributor_id");

                    b.Property<int>("HashKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("hash_key_version");

                    b.Property<byte[]>("LabelCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("label_ciphertext");

                    b.Property<byte[]>("LabelGroupingKey")
                        .HasColumnType("bytea")
                        .HasColumnName("label_grouping_key");

                    b.Property<byte[]>("PhoneHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phone_hash");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("verdict");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_spam_reports");

                    b.HasIndex("PhoneHash", "ContributorId")
                        .IsUnique()
                        .HasDatabaseName("ix_spam_reports_phone_hash_contributor_id");

                    b.ToTable("spam_reports", (string)null);
                });

            modelBuilder.Entity("Tranqui.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_firebase_uid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tranqui.Domain.Users.User", b =>
                {
                    b.OwnsMany("Tranqui.Domain.Users.Consent", "Consents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("AcceptedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("accepted_at");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("type");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("version");

                            b1.HasKey("Id")
                                .HasName("pk_user_consents");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_user_consents_user_id");

                            b1.ToTable("user_consents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_consents_users_user_id");
                        });

                    b.Navigation("Consents");
                });
#pragma warning restore 612, 618
        }
    }
}
